name: Deploy Nashama Store to GitHub Pages

on:
  push:
    branches:
      - main # العمل فقط على الفرع الرئيسي

# إعطاء الصلاحيات اللازمة للروبوت للرفع المباشر
permissions:
  contents: read
  pages: write
  id-token: write

# منع تشغيل أكثر من عملية رفع في نفس الوقت
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies 📦
        run: npm install --legacy-peer-deps

      - name: Build Project 🏗️
        run: |
          npm run build

          # خدعة الـ SPA الأساسية
          cp dist/index.html dist/404.html

          # خدعة الـ SEO لمتجر نشامى
          mkdir -p dist/search dist/offers dist/trends dist/category dist/brands dist/product dist/return-policy dist/service-usage
          cp dist/index.html dist/search/index.html
          cp dist/index.html dist/offers/index.html
          cp dist/index.html dist/trends/index.html
          cp dist/index.html dist/category/index.html
          cp dist/index.html dist/brands/index.html
          cp dist/index.html dist/product/index.html
          cp dist/index.html dist/return-policy/index.html
          cp dist/index.html dist/service-usage/index.html

          # إضافة النطاق المخصص (CNAME)
          echo "nashamastore.com" > dist/CNAME

      - name: Setup Pages 🔧
        uses: actions/configure-pages@v4

      - name: Upload Artifact 📤
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist" # رفع مجلد البناء فقط كحزمة واحدة

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
